# Copied from azure-rest-api-specs/.github/workflows/_reusable-eng-tools-test.yaml

name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu, windows]
        node-version: [20, 22]
        exclude:
          - os: ubuntu
            node-version: 22
          - os: windows
            node-version: 20

    runs-on: ${{ fromJSON('{"ubuntu":"ubuntu-24.04", "windows":"windows-2022"}')[matrix.os] }}

    steps:
      - if: runner.os == 'Windows'
        run: git config --global core.longpaths true
        shell: pwsh

      - uses: actions/checkout@v6

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        run: |
          echo "::group::npm ci"
          npm ci
          echo "::endgroup::"
          echo "::group::npm ls -a"
          npm ls -a || true
          echo "::endgroup::"
        shell: bash

      - name: Build
        run: npm run build
        shell: pwsh

      - name: Lint
        run: npm run lint
        shell: pwsh

      - name: Check Formatting
        run: npm run format:check:ci
        shell: pwsh

      - name: Test
        run: npm run test:ci
        shell: pwsh

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report-${{ matrix.os }}-${{ matrix.node-version }}
          path: ./coverage
          if-no-files-found: ignore
